app/routes/name_management.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import db, Record

bp = Blueprint('name_management', __name__, url_prefix='/name_management')


@bp.route('/menu', methods=['GET'])
def name_management_menu():
    return render_template('name_management_menu.html')

@bp.route('/')
def index():
    return render_template('name_management_menu.html')


@bp.route('/add', methods=['GET', 'POST'])
def add_name():
    if request.method == 'POST':
        name = request.form['name']
        if not name:
            flash('Name is required!', 'error')
            return redirect(url_for('name_management.add_name'))

        existing_record = Record.query.filter(db.func.lower(Record.name) == name.lower()).first()
        if existing_record:
            flash(f"Name '{name}' already exists in the database.", 'error')
        else:
            new_record = Record(name=name)
            db.session.add(new_record)
            db.session.commit()
            flash(f"Name '{name}' added to database.", 'success')

        return redirect(url_for('name_management.add_name'))

    return render_template('add_name.html')

@bp.route('/delete', methods=['GET', 'POST'])
def delete_name():
    if request.method == 'POST':
        record_id = request.form['record_id']
        record = db.session.get(Record, record_id)  # Updated to use Session.get()
        if record:
            db.session.delete(record)
            db.session.commit()
            flash(f"Name '{record.name}' deleted from the database.", 'success')
        else:
            flash('Record not found.', 'error')

        return redirect(url_for('name_management.delete_name'))

    records = Record.query.all()
    return render_template('delete_name.html', records=records)


@bp.route('/view', methods=['GET'])
def view_database():
    records = Record.query.all()
    return render_template('view_database.html', records=records)


@bp.route('/exception', methods=['GET'])
def manage_exceptions():
    return render_template('manage_exceptions.html')

app/routes/theme_management.py
from flask import Blueprint, render_template

bp = Blueprint('theme_management', __name__, url_prefix='/theme_management')

@bp.route('/')
def index():
    return render_template('theme_management/index.html')

@bp.route('/add', methods=['GET', 'POST'])
def add_theme():
    # Logic for adding a theme will go here
    return render_template('theme_management/add_theme.html')

@bp.route('/update', methods=['GET', 'POST'])
def update_theme():
    # Logic for updating a theme will go here
    return render_template('theme_management/update_theme.html')

@bp.route('/delete', methods=['GET', 'POST'])
def delete_theme():
    # Logic for deleting a theme will go here
    return render_template('theme_management/delete_theme.html')

app/routes/view.py
from flask import Blueprint, render_template
from app.models import TalkAssignment
from datetime import datetime

bp = Blueprint('view', __name__, url_prefix='/view')

@bp.route('/assignments', methods=['GET'])
def view_assignments():
    # Query TalkAssignment instead of Record
    assignments_query = TalkAssignment.query.filter(TalkAssignment.date != None).order_by(TalkAssignment.date).all()

    assignments = {}
    for assignment in assignments_query:
        date = assignment.date
        year_month = date.strftime('%Y %B')  # Format: '2024 August'
        if year_month not in assignments:
            assignments[year_month] = []
        assignments[year_month].append(assignment)

    return render_template('view_assignments.html', assignments=assignments)

app/templates/sidebars/exception_sidebar.html
<h2>Manage Exceptions</h2>
<ul class="list-unstyled">
    <li><a href="{{ url_for('exception.add_exception') }}" class="{% if request.endpoint == 'exception.add_exception' %}active{% endif %}">Add Exception</a></li>
    <li><a href="{{ url_for('exception.update_exception') }}" class="{% if request.endpoint == 'exception.update_exception' %}active{% endif %}">Update Exception</a></li>
    <li><a href="{{ url_for('exception.remove_exception') }}" class="{% if request.endpoint == 'exception.remove_exception' %}active{% endif %}">Remove Exception</a></li>
    <li><a href="{{ url_for('exception.set_available') }}" class="{% if request.endpoint == 'exception.set_available' %}active{% endif %}">Set as Available</a></li>
</ul>

app/templates/sidebars/manage_assignments_menu.html
<h2>Manage Assignments</h2>
<ul>
    <li><a href="{{ url_for('assign.assign_talk') }}" class="{% if request.endpoint == 'assign.assign_talk' %}active{% endif %}">Assign Talk</a></li>
    <li><a href="{{ url_for('assign.manage_assignments') }}" class="{% if request.endpoint == 'assign.manage_assignments' %}active{% endif %}">Manage Assignments</a></li>
    <li><a href="{{ url_for('view.view_assignments') }}" class="{% if request.endpoint == 'view.view_assignments' %}active{% endif %}">View Assignments</a></li>
</ul>

app/templates/sidebars/name_management_menu.html
<h2>Name Management</h2>
<ul class="list-unstyled">
    <li><a class="d-block py-2" href="{{ url_for('name_management.add_name') }}">Add Name</a></li>
    <li><a class="d-block py-2" href="{{ url_for('name_management.view_database') }}">View Database</a></li>
    <li><a class="d-block py-2" href="{{ url_for('name_management.delete_name') }}">Delete Name</a></li>
    <li>
        <a class="d-block py-2" href="#exceptions-submenu" data-toggle="collapse" aria-expanded="false" aria-controls="exceptions-submenu">Manage Exceptions</a>
        <ul id="exceptions-submenu" class="collapse list-unstyled pl-3">
            <li><a class="d-block py-1" href="{{ url_for('exception.add_exception') }}">Add Exception</a></li>
            <li><a class="d-block py-1" href="{{ url_for('exception.update_exception') }}">Update Exception</a></li>
            <li><a class="d-block py-1" href="{{ url_for('exception.remove_exception') }}">Remove Exception</a></li>
            <li><a class="d-block py-1" href="{{ url_for('exception.set_available') }}">Set as Available</a></li>
        </ul>
    </li>
    <li><a class="d-block py-2" href="{{ url_for('import_names.import_names') }}">Import Names</a></li>
</ul>

app/templates/sidebars/theme_management_sidebar.html
<h2>Theme Management</h2>
<ul class="list-unstyled">
    <li>
        <a href="#theme-submenu" data-toggle="collapse" aria-expanded="false" aria-controls="theme-submenu">Manage Themes</a>
        <ul id="theme-submenu" class="collapse list-unstyled pl-3">
            <li><a href="{{ url_for('theme_management.add_theme') }}" class="{% if request.endpoint == 'theme_management.add_theme' %}active{% endif %}">Add Theme</a></li>
            <li><a href="{{ url_for('theme_management.update_theme') }}" class="{% if request.endpoint == 'theme_management.update_theme' %}active{% endif %}">Update Theme</a></li>
            <li><a href="{{ url_for('theme_management.delete_theme') }}" class="{% if request.endpoint == 'theme_management.delete_theme' %}active{% endif %}">Delete Theme</a></li>
        </ul>
    </li>
</ul>